# Generated by Django 5.0.6 on 2024-07-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='paint',
            field=models.ImageField(upload_to='boards/'),
        ),
    ]
